config/routes.rb
Rails.application.routes.draw do

 

  resources :organismes
  resources :organismes
  resources :organismes
  devise_for :deviseusers , controllers: { registrations: 'deviseusers/registrations' }
  resources :deviseusers
  resources :organisme_referents
  
  
  
  scope "(:locale)", locale: /en|fr/ do 
    root'static_pages#home'
    
    resources :usagers do 
      get 'myLsitOfUsers'
    end
  
  end

  
  
  
  
  get 'usagers/:nom' => 'usagers#show', as: :show_usager

 

end

app/models/organisme_referent.rb
class OrganismeReferent < ActiveRecord::Base
    belongs_to :usager
end

app/controllers/organisme_referents_controller.rb
class OrganismeReferentsController < ApplicationController
  before_action :set_organisme_referent, only: [:show, :edit, :update, :destroy]

  # GET /organisme_referents
  # GET /organisme_referents.json
  def index
    @organisme_referents = OrganismeReferent.all
  end

  # GET /organisme_referents/1
  # GET /organisme_referents/1.json
  def show
  end

  # GET /organisme_referents/new
  def new
    @organisme_referent = OrganismeReferent.new
  end

  # GET /organisme_referents/1/edit
  def edit
  end

  # POST /organisme_referents
  # POST /organisme_referents.json
  def create
    @organisme_referent = OrganismeReferent.new(organisme_referent_params)

    respond_to do |format|
      if @organisme_referent.save
        format.html { redirect_to @organisme_referent, notice: 'Organisme referent was successfully created.' }
        format.json { render :show, status: :created, location: @organisme_referent }
      else
        format.html { render :new }
        format.json { render json: @organisme_referent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisme_referents/1
  # PATCH/PUT /organisme_referents/1.json
  def update
    respond_to do |format|
      if @organisme_referent.update(organisme_referent_params)
        format.html { redirect_to @organisme_referent, notice: 'Organisme referent was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisme_referent }
      else
        format.html { render :edit }
        format.json { render json: @organisme_referent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisme_referents/1
  # DELETE /organisme_referents/1.json
  def destroy
    @organisme_referent.destroy
    respond_to do |format|
      format.html { redirect_to organisme_referents_url, notice: 'Organisme referent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisme_referent
      @organisme_referent = OrganismeReferent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisme_referent_params
      params.require(:organisme_referent).permit(:nomOrganisme, :adresseNoCivique, :adresseRue, :adresseVille, :adresseProvince, :adresseEtat, :adresseCodePostal, :telephoneBureau, :adresseTelecopie, :courriel, :siteWeb)
    end
end

app/helpers/organisme_referents_helper.rb
module OrganismeReferentsHelper
end

app/views/organisme_referents/_form.html.erb
<%= simple_form_for(@organisme_referent) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nomOrganisme %>
    <%= f.input :adresseNoCivique %>
    <%= f.input :adresseRue %>
    <%= f.input :adresseVille %>
    <%= f.input :adresseProvince %>
    <%= f.input :adresseEtat %>
    <%= f.input :adresseCodePostal %>
    <%= f.input :telephoneBureau %>
    <%= f.input :adresseTelecopie %>
    <%= f.input :courriel %>
    <%= f.input :siteWeb %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organisme_referents/edit.html.erb
<h1>Editing Organisme Referent</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisme_referent %> |
<%= link_to 'Back', organisme_referents_path %>

app/views/organisme_referents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organisme Referents</h1>

<hr />
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nomorganisme</th>
      <th>Adressenocivique</th>
      <th>Adresserue</th>
      <th>Adresseville</th>
      <th>Adresseprovince</th>
      <th>Adresseetat</th>
      <th>Adressecodepostal</th>
      <th>Telephonebureau</th>
      <th>Adressetelecopie</th>
      <th>Courriel</th>
      <th>Siteweb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisme_referents.each do |organisme_referent| %>
      <tr>
        <td><%= organisme_referent.nomOrganisme %></td>
        <td><%= organisme_referent.adresseNoCivique %></td>
        <td><%= organisme_referent.adresseRue %></td>
        <td><%= organisme_referent.adresseVille %></td>
        <td><%= organisme_referent.adresseProvince %></td>
        <td><%= organisme_referent.adresseEtat %></td>
        <td><%= organisme_referent.adresseCodePostal %></td>
        <td><%= organisme_referent.telephoneBureau %></td>
        <td><%= organisme_referent.adresseTelecopie %></td>
        <td><%= organisme_referent.courriel %></td>
        <td><%= organisme_referent.siteWeb %></td>
        <td><%= link_to 'Show', organisme_referent %></td>
        <td><%= link_to 'Edit', edit_organisme_referent_path(organisme_referent) %></td>
        <td><%= link_to 'Destroy', organisme_referent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Organisme referent', new_organisme_referent_path %>
<br>
<%= link_to 'Retour page accueil', root_path %>

app/views/organisme_referents/new.html.erb
<h1>New Organisme Referent</h1>

<%= render 'form' %>

<%= link_to 'Back', organisme_referents_path %>

app/views/organisme_referents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nomorganisme:</strong>
  <%= @organisme_referent.nomOrganisme %>
</p>

<p>
  <strong>Adressenocivique:</strong>
  <%= @organisme_referent.adresseNoCivique %>
</p>

<p>
  <strong>Adresserue:</strong>
  <%= @organisme_referent.adresseRue %>
</p>

<p>
  <strong>Adresseville:</strong>
  <%= @organisme_referent.adresseVille %>
</p>

<p>
  <strong>Adresseprovince:</strong>
  <%= @organisme_referent.adresseProvince %>
</p>

<p>
  <strong>Adresseetat:</strong>
  <%= @organisme_referent.adresseEtat %>
</p>

<p>
  <strong>Adressecodepostal:</strong>
  <%= @organisme_referent.adresseCodePostal %>
</p>

<p>
  <strong>Telephonebureau:</strong>
  <%= @organisme_referent.telephoneBureau %>
</p>

<p>
  <strong>Adressetelecopie:</strong>
  <%= @organisme_referent.adresseTelecopie %>
</p>

<p>
  <strong>Courriel:</strong>
  <%= @organisme_referent.courriel %>
</p>

<p>
  <strong>Siteweb:</strong>
  <%= @organisme_referent.siteWeb %>
</p>

<%= link_to 'Edit', edit_organisme_referent_path(@organisme_referent) %> |
<%= link_to 'Back', organisme_referents_path %>