config/routes.rb
Rails.application.routes.draw do

 

  resources :organismes
  resources :organismes
  resources :organismes
  devise_for :deviseusers , controllers: { registrations: 'deviseusers/registrations' }
  resources :deviseusers
  resources :organisme_referents
  
  
  
  scope "(:locale)", locale: /en|fr/ do 
    root'static_pages#home'
    
    resources :usagers do 
      get 'myLsitOfUsers'
    end
  
  end

  
  
  
  
  get 'usagers/:nom' => 'usagers#show', as: :show_usager

 

end

app/models/usager.rb
class Usager < ActiveRecord::Base

   
    validates :nom, presence: true, length: { minimum: 5}
    validates :role, presence: true, length: { minimum: 5}
    
    belongs_to :deviseuser
    
    has_many :organisme_referent
    
end

app/controllers/usagers_controller.rb
class UsagersController < ApplicationController
  before_action :authenticate_deviseuser!
  
  before_action :set_usager, only: [:show, :edit, :update, :destroy]


  # GET /usagers
  # GET /usagers.json
  def index
    @usagers = Usager.all
  end

  # GET /usagers/1
  # GET /usagers/1.json
  def show
    
  end

  # GET /usagers/new
  def new
    @usager = Usager.new

  end

  # GET /usagers/1/edit
  def edit
  end

  # POST /usagers
  # POST /usagers.json
  def create
    @usager = current_deviseuser.usagers.build(usager_params)   #Permet de referer l'id du createur
   
    respond_to do |format|
      if @usager.save
        
        format.html { redirect_to @usager, notice: 'Usager was successfully created.' }
        format.json { render :show, status: :created, location: @usager }
      else
        format.html { render :new }
        format.json { render json: @usager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usagers/1
  # PATCH/PUT /usagers/1.json
  def update
    respond_to do |format|
      if @usager.update(usager_params)
        format.html { redirect_to @usager, notice: 'Usager was successfully updated.' }
        format.json { render :show, status: :ok, location: @usager }
      else
        format.html { render :edit }
        format.json { render json: @usager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usagers/1
  # DELETE /usagers/1.json
  def destroy
    @usager.destroy
    respond_to do |format|
      format.html { redirect_to usagers_url, notice: 'Usager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usager
      @usager = Usager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usager_params
      params.require(:usager).permit(:courriel, :nom, :motPasse, :role)
    end
end

app/helpers/usagers_helper.rb
module UsagersHelper
end

app/views/usagers/_form.html.erb
<%= simple_form_for(@usager) do |f| %>
  <%= f.error_notification %>


  <div class="form-inputs">
    <%= f.input :courriel %>
    <%= f.input :nom %>
    <%= f.input :motPasse %>
    <%= f.label :role %>
    
    <% if current_deviseuser.role== 'Directeur'%>
      <br/>  <%= f.select(:role, options_for_select(['Directeur', ' Coordonateur', 'Adjoint Coordonateur', 'Intervenant'])) %>
  
    <% else %>
        <%= f.select(:role, options_for_select([' Coordonateur', 'Adjoint Coordonateur', 'Intervenant'])) %>
    <% end %>
 
  </div>

  <div class="form-actions">
    <br/>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/usagers/edit.html.erb
<h1>Editing Usager</h1>

<%= render 'form' %>

<%= link_to 'Show', @usager %> |
<%= link_to 'Back', usagers_path %>

app/views/usagers/index.html.erb
<h1>Voici votre liste d'usagers</h1>



<hr />
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('usagers.nom')%></th>
      <th><%= t('usagers.courriel')%></th>
      <th><%= t('usagers.nom')%></th>
      <th><%= t('usagers.role')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usagers.each do |usager| %>
    <% if current_deviseuser.id == usager.deviseuser_id%>

      <tr>
        <td><%= usager.courriel %></td>
        <td><%= usager.nom %></td>
        <td><%= usager.motPasse %></td>
        <td><%= usager.role %></td>
        <td><%= link_to t('Show'), usager, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to t('Edit'), edit_usager_path(usager),class: 'btn btn-mini btn-primary'  %></td>
        <td><%= link_to t('Destroy'), usager, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %></td>
      </tr>
      
    <% end %>
    <% end %>

  </tbody>
</table>

<br>
<%= link_to 'Nouveau Usager', new_usager_path, class: 'btn btn-mini btn-primary' %>


<% if current_deviseuser.role == "Coordonateur"%>
<%= link_to 'Nouveau organisme referent', new_organisme_referent_path, class: 'btn btn-mini btn-primary' %>
<% end %>

<br>
<%= link_to 'Retour page accueil', root_path %>

app/views/usagers/new.html.erb
<h1>Creer un nouvel usager</h1>

<%= render 'form' %>

<%= link_to 'Back', usagers_path %>

app/views/usagers/show.html.erb
<h1><%= @usager.nom %></h1>

<hr />
<p>
  <strong>Courriel:</strong>
  <%= @usager.courriel %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @usager.nom %>
</p>

<p>
  <strong>Motpasse:</strong>
  <%= @usager.motPasse %>
</p>

<p>
  <strong>Role:</strong>
  <%= @usager.role %>
</p>

<%= link_to 'Edit', edit_usager_path(@usager) %> |
<%= link_to 'Back', usagers_path %>