config/routes.rb
Rails.application.routes.draw do

 

  resources :organismes
  resources :organismes
  resources :organismes
  devise_for :deviseusers , controllers: { registrations: 'deviseusers/registrations' }
  resources :deviseusers
  resources :organisme_referents
  
  
  
  scope "(:locale)", locale: /en|fr/ do 
    root'static_pages#home'
    
    resources :usagers do 
      get 'myLsitOfUsers'
    end
  
  end

  
  
  
  
  get 'usagers/:nom' => 'usagers#show', as: :show_usager

 

end

app/models/organisme.rb
class Organisme < ActiveRecord::Base
    belongs_to :deviseuser
end

app/controllers/organismes_controller.rb
class OrganismesController < ApplicationController
  before_action :set_organisme, only: [:show, :edit, :update, :destroy]

  # GET /organismes
  # GET /organismes.json
  def index
    @organismes = Organisme.all
  end

  # GET /organismes/1
  # GET /organismes/1.json
  def show
  end

  # GET /organismes/new
  def new
    @organisme = Organisme.new
  end

  # GET /organismes/1/edit
  def edit
  end

  # POST /organismes
  # POST /organismes.json
  def create
    #@organisme = Organisme.new(organisme_params)
    @organisme = current_deviseuser.organismes.build(organisme_params)   #Permet de referer l'id du createur         
    
    respond_to do |format|
      if @organisme.save
        format.html { redirect_to @organisme, notice: 'Organisme was successfully created.' }
        format.json { render :show, status: :created, location: @organisme }
      else
        format.html { render :new }
        format.json { render json: @organisme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organismes/1
  # PATCH/PUT /organismes/1.json
  def update
    respond_to do |format|
      if @organisme.update(organisme_params)
        format.html { redirect_to @organisme, notice: 'Organisme was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisme }
      else
        format.html { render :edit }
        format.json { render json: @organisme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organismes/1
  # DELETE /organismes/1.json
  def destroy
    @organisme.destroy
    respond_to do |format|
      format.html { redirect_to organismes_url, notice: 'Organisme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisme
      @organisme = Organisme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisme_params
      params.require(:organisme).permit(:nom, :adresse, :telephone, :courriel)
    end
end

app/helpers/organismes_helper.rb
module OrganismesHelper
end

app/views/organismes/_form.html.erb
<%= simple_form_for(@organisme) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom %>
    <%= f.input :adresse %>
    <%= f.input :telephone %>
    <%= f.input :courriel %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organismes/edit.html.erb
<h1>Editing Organisme</h1>

<%= render 'form' %>

<%= link_to 'Show', @organisme %> |
<%= link_to 'Back', organismes_path %>

app/views/organismes/index.html.erb
<p id="notice"><%= notice %></p>

<%= current_deviseuser.id%>

<h1>Listing Organismes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Adresse</th>
      <th>Telephone</th>
      <th>Courriel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organismes.each do |organisme| %>
    <%if current_deviseuser.id == organisme.deviseuser_id%>
      <tr>
        <td><%= organisme.nom %></td>
        <td><%= organisme.adresse %></td>
        <td><%= organisme.telephone %></td>
        <td><%= organisme.courriel %></td>
        <td><%= link_to 'Show', organisme %></td>
        <td><%= link_to 'Edit', edit_organisme_path(organisme) %></td>
        <td><%= link_to 'Destroy', organisme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisme', new_organisme_path %>

app/views/organismes/new.html.erb
<h1>New Organisme</h1>

<%= render 'form' %>

<%= link_to 'Back', organismes_path %>

app/views/organismes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @organisme.nom %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @organisme.adresse %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @organisme.telephone %>
</p>

<p>
  <strong>Courriel:</strong>
  <%= @organisme.courriel %>
</p>

<%= link_to 'Edit', edit_organisme_path(@organisme) %> |
<%= link_to 'Back', organismes_path %>