config/routes.rb
Rails.application.routes.draw do

 

  resources :organismes
  resources :organismes
  resources :organismes
  devise_for :deviseusers , controllers: { registrations: 'deviseusers/registrations' }
  resources :deviseusers
  resources :organisme_referents
  
  
  
  scope "(:locale)", locale: /en|fr/ do 
    root'static_pages#home'
    
    resources :usagers do 
      get 'myLsitOfUsers'
    end
  
  end

  
  
  
  
  get 'usagers/:nom' => 'usagers#show', as: :show_usager

 

end

app/views/layouts/_header.html.erb
    <div class="span12">
        <div class="navbar">
            <div class="nav-bar-inner">
                <%= link_to t('site_title'), root_path, class: 'brand' %>
                
                 <%= link_to 'Me deconnecter',destroy_deviseuser_session_path, method: :delete%>
                
                <ul class="nav">
                    <li class= "divider-vertical"></li>
                    
                    <%# Usagers %>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%=t('usagers.menu')%> </a>
                        <ul class="dropdown-menu">
                        </ul>
                    </li>
                </ul>    
                    
                   
            </div>
        </nav>
    <div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value | %>
 <div class="row">
    <div class="span12">
            <div class="alert alert-<%= key %>"><%= value.html_safe %> </div>
             
    </div>
 </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div class="container">
  <%= render 'layouts/header' %>
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

<script type="text/javascript">
  $('.alert').delay(7000).fadeOut();
</script>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

</body>
</html>